######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 9 12:20:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += mxit.h
SOURCES += main.cpp mxit.cpp
